In [4]:
from joblib import dump, load
import numpy as np
model = load('Dragon.joblib')

In [5]:
input = np.array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.2397918 , -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034]])
model.predict(input)

array([22.541])

In [6]:
input = np.array([[-0.43942506,  65.12628155, 1.12165014, 80.27288841, -18.42262747,
       -75.2397918 , -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -75.97491834,  85.41164221, -1.86091034]])
model.predict(input)

array([29.981])

In [7]:
input = np.array([[-0.43942506,  65.12628155, 1.12165014, 80.27288841, -18.42262747,
       -75.2397918 , -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -75.97491834,  85.41164221, -1.86091034]])
model.predict(input)

array([29.981])

In [8]:
input = np.array([[-9.43942506,  665.12628155, 12.12165014, -80.27288841, -18.42262747,
       -75.2397918 , -1.31238772,  -2.61111401, -15.0016859 , 0.5778192 ,
       -75.97491834,  85.41164221, -1.86091034]])
model.predict(input)

array([42.809])